spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/smart_oa?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai}
    username: ${DB_USERNAME:smartoa}
    password: ${DB_PASSWORD:smartoa_dev}
  flyway.placeholders.passwordHash: ${DEMO_PASSWORD_HASH:$2a$10$Dow1E3ycUvGIX5FYmRFZhe5LmZ/0kw7E68mB260d9XwbQmzqlT5I6}
